services:
  - type: web
    name: lead-management-api
    env: python
    buildCommand: pip install -r lead_management/requirements.txt && python lead_management/manage.py collectstatic --noinput && python lead_management/manage.py migrate
    startCommand: gunicorn --bind 0.0.0.0:$PORT --chdir lead_management lead_management.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*" # Update this with your actual domain later
